[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.19"
optimizer_runs = 200

# Fuzz configuration
[fuzz]
runs = 500
max_test_rejects = 65536

# Test configuration
[invariant]
runs = 256
depth = 30

# Formatting
fmt = true

# Gas reporting
gas_reports = ["*"]
gas_reports_ignore = ["@openzeppelin/*"]