[profile.default]
solc_version = "0.8.25"
evm_version  = "paris"
optimizer = true
optimizer_runs = 200
via_ir = false
bytecode_hash = "ipfs"
src = "src"
out = "out"
libs = ["lib"]
ffi = false
fs_permissions = [{ access = "read", path = "./"}]

# Fast inner-loop dev: fewer runs, more readable asm
[profile.dev]
optimizer = true
optimizer_runs = 50
via_ir = false
evm_version = "paris"

# CI: deterministic, stricter, full optimizer
[profile.ci]
optimizer = true
optimizer_runs = 10_000
via_ir = true
evm_version = "paris"
revert_strings = "strip"
bytecode_hash = "none"
deny_warnings = true

# Gas benchmarking: crank optimizer + viaIR
[profile.gas]
optimizer = true
optimizer_runs = 10_000
via_ir = true
evm_version = "paris"

# Fuzz-focused: keep builds quick
[profile.fuzz]
optimizer = true
optimizer_runs = 200
via_ir = false
fuzz_runs = 256

# Coverage build (often slower)
[profile.coverage]
optimizer = false
via_ir = false

# Formatter: forge fmt respects these
[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
int_types = "long"
quote_style = "double"
