name: Foundry Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
          
      - name: Install dependencies
        run: forge install OpenZeppelin/openzeppelin-contracts --no-commit
        
      - name: Run tests
        run: forge test --verbosity 2
        
      - name: Run tests with gas report
        run: forge test --gas-report
        
      - name: Check formatting
        run: forge fmt --check
        
      - name: Run slither analysis
        run: |
          pip install slither-analyzer
          slither . --exclude-dependencies